language: c++

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  
install:
  #- sudo apt-get install g++-multilib -y --force-yes
  #- sudo apt-get install haxe -y --force-yes
  #- mkdir ~/haxelib
  #- haxelib setup ~/haxelib
  #- haxelib install hxcpp
  #- haxelib install msignal
  #- haxelib install munit
  #- haxelib dev itsumono ./src

script:
  #- haxelib run munit test -browser firefox -kill-browser -debug
  cd ~/.mozilla/firefox/
  ls -la
  #firefox http://www.example.com